[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  environment = { NODE_VERSION = "10.15.3", NODE_ENV = "production" }

[dev]
  framework = "#custom"
  command = "npm run start"
  publish = "dist"
  port = 3005
  targetPort = 8181
  NODE_ENV = "development"

[[redirects]]
  from = "/testredirect"
  to = "/2020/05/persistent-session-data-via-localstorage-in-phoenix-liveview"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
